version: "3.8"
services:
 game_app:
    build: .
    working_dir: /app
    container_name: game_app
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
      - PORT=8000
    volumes:
      - ./app/:/app
    tty: true
    init: true
    command: yarn dev
